# Flaky Tests Investigation Results

## Overall Results
# Flaky Tests Summary
Run on: Mon Apr  7 13:23:50 UTC 2025
Iterations per test: 10

| Test | Passed | Failed | Success Rate | Avg Duration | Issues |
|------|--------|--------|-------------|--------------|--------|
| `tests::signer::v0::multiple_miners_empty_sortition` | 10 | 0 | 100.00% | 201.24s |  |
| `tests::nakamoto_integrations::test_tenure_extend_from_flashblocks` | 10 | 0 | 100.00% | 116.65s |  |
| `tests::signer::v0::single_miner_empty_sortition` | 10 | 0 | 100.00% | 162.11s |  |
| `tests::signer::v0::block_proposal_rejection` | 10 | 0 | 100.00% | 74.96s |  |
| `tests::nakamoto_integrations::nakamoto_lockup_events` | 10 | 0 | 100.00% | 80.78s |  |
| `net::tests::convergence::test_walk_star_15_plain` | 9 | 1 | 90.00% | 83.57s | assertion `left == right` failed... |
| `tests::nakamoto_integrations::skip_mining_long_tx` | 10 | 0 | 100.00% | 98.31s |  |
| `tests::signer::v0::partial_tenure_fork` | 10 | 0 | 100.00% | 257.44s |  |
| `tests::signer::v0::global_acceptance_depends_on_block_announcement` | 8 | 2 | 80.00% | 82.69s | thread 'tests::signer::v0::global_acceptance_depends_on_bloc... |
| `net::tests::convergence::test_walk_ring_15_org_biased` | 10 | 0 | 100.00% | 97.82s |  |
| `tests::nakamoto_integrations::follower_bootup_across_multiple_cycles` | 10 | 0 | 100.00% | 372.74s |  |
| `net::tests::convergence::test_walk_star_allowed_15` | 10 | 0 | 100.00% | 83.11s |  |

## Failure Details
### block_proposal_rejection
No failures detected for this test

### follower_bootup_across_multiple_cycles
No failures detected for this test

### global_acceptance_depends_on_block_announcement
Found failures:
#### Iteration 10
# Failure - Iteration 10
```
INFO [1744045661.754486] [stacks-signer/src/v0/signer.rs:953] [signer_runloop:3000] Cycle #11 Signer #2: Received a block validate response: Ok(BlockValidateOk { signer_signature_hash: 40f5627d223d7fdec04104d1c69fb7f4715834646347346c70ef0d4e1777bb67, cost: ExecutionCost { write_length: 0, write_count: 0, read_length: 0, read_count: 0, runtime: 0 }, size: 180, validation_time_ms: 18 })
ERRO [1744045690.942250] [testnet/stacks-node/src/tests/nakamoto_integrations.rs:694] [tests::signer::v0::global_acceptance_depends_on_block_announcement] Timed out waiting for check to process

thread 'tests::signer::v0::global_acceptance_depends_on_block_announcement' panicked at testnet/stacks-node/src/tests/signer/v0.rs:8352:6:
Timed out waiting for block acceptance of N+1 by a majority of signers: "Timed out"
stack backtrace:
   0:     0x55f547d5f172 - std::backtrace_rs::backtrace::libunwind::trace::hde5393a3699c97ba
                               at /rustc/2fa8b11f0933dae9b4e5d287cc10c989218e8b36/library/std/src/../../backtrace/src/backtrace/libunwind.rs:117:9
   1:     0x55f547d5f172 - std::backtrace_rs::backtrace::trace_unsynchronized::h3ff2a1f207cc6214
                               at /rustc/2fa8b11f0933dae9b4e5d287cc10c989218e8b36/library/std/src/../../backtrace/src/backtrace/mod.rs:66:14
   2:     0x55f547d5f172 - std::sys::backtrace::_print_fmt::h59669f906692834a
                               at /rustc/2fa8b11f0933dae9b4e5d287cc10c989218e8b36/library/std/src/sys/backtrace.rs:66:9
   3:     0x55f547d5f172 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h54e65d53802d6f14
                               at /rustc/2fa8b11f0933dae9b4e5d287cc10c989218e8b36/library/std/src/sys/backtrace.rs:39:26
--
```

#### Iteration 2
# Failure - Iteration 2
```
INFO [1744044910.383705] [stacks-signer/src/v0/signer.rs:953] [signer_runloop:3000] Cycle #11 Signer #4: Received a block validate response: Ok(BlockValidateOk { signer_signature_hash: 16ea6478ede3816759a3fae267fe4e4aa625307927653d96cff78a450a7f4867, cost: ExecutionCost { write_length: 0, write_count: 0, read_length: 0, read_count: 0, runtime: 0 }, size: 180, validation_time_ms: 24 })
ERRO [1744044939.880671] [testnet/stacks-node/src/tests/nakamoto_integrations.rs:694] [tests::signer::v0::global_acceptance_depends_on_block_announcement] Timed out waiting for check to process

thread 'tests::signer::v0::global_acceptance_depends_on_block_announcement' panicked at testnet/stacks-node/src/tests/signer/v0.rs:8352:6:
Timed out waiting for block acceptance of N+1 by a majority of signers: "Timed out"
stack backtrace:
   0:     0x555ce6ab8172 - std::backtrace_rs::backtrace::libunwind::trace::hde5393a3699c97ba
                               at /rustc/2fa8b11f0933dae9b4e5d287cc10c989218e8b36/library/std/src/../../backtrace/src/backtrace/libunwind.rs:117:9
   1:     0x555ce6ab8172 - std::backtrace_rs::backtrace::trace_unsynchronized::h3ff2a1f207cc6214
                               at /rustc/2fa8b11f0933dae9b4e5d287cc10c989218e8b36/library/std/src/../../backtrace/src/backtrace/mod.rs:66:14
   2:     0x555ce6ab8172 - std::sys::backtrace::_print_fmt::h59669f906692834a
                               at /rustc/2fa8b11f0933dae9b4e5d287cc10c989218e8b36/library/std/src/sys/backtrace.rs:66:9
   3:     0x555ce6ab8172 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h54e65d53802d6f14
                               at /rustc/2fa8b11f0933dae9b4e5d287cc10c989218e8b36/library/std/src/sys/backtrace.rs:39:26
--
```


### multiple_miners_empty_sortition
No failures detected for this test

### nakamoto_lockup_events
No failures detected for this test

### partial_tenure_fork
No failures detected for this test

### single_miner_empty_sortition
No failures detected for this test

### skip_mining_long_tx
No failures detected for this test

### test_tenure_extend_from_flashblocks
No failures detected for this test

### test_walk_ring_15_org_biased
No failures detected for this test

### test_walk_star_15_plain
Found failures:
#### Iteration 1
# Failure - Iteration 1
```
INFO [1744040189.467296] [stackslib/src/net/stackerdb/mod.rs:509] [ThreadId(3)] No stacker DB config for S11040G2081040G2081040G2081040G20AGVB6D3.db-2
INFO [1744040189.470889] [stackslib/src/net/p2p.rs:2013] [ThreadId(3)] Neighbor accepted!, public key: None, address: 127.0.0.1

thread '<unnamed>' panicked at stackslib/src/net/tests/convergence.rs:1099:17:
assertion `left == right` failed
  left: [QualifiedContractIdentifier { issuer: StandardPrincipalData(S100000000000000000000J197CZ), name: ContractName("db-0") }, QualifiedContractIdentifier { issuer: StandardPrincipalData(S1G2081040G2081040G2081040G208105NK8PE5), name: ContractName("db-1") }, QualifiedContractIdentifier { issuer: StandardPrincipalData(S11040G2081040G2081040G2081040G20AGVB6D3), name: ContractName("db-2") }, QualifiedContractIdentifier { issuer: StandardPrincipalData(S11G60R30C1G60R30C1G60R30C1G60R30DM01V8D), name: ContractName("db-3") }, QualifiedContractIdentifier { issuer: StandardPrincipalData(S12081040G2081040G2081040G2081040HYKVZCC), name: ContractName("db-4") }, QualifiedContractIdentifier { issuer: StandardPrincipalData(S12GA1850M2GA1850M2GA1850M2GA1850MPMXPEG), name: ContractName("db-5") }, QualifiedContractIdentifier { issuer: StandardPrincipalData(S130C1G60R30C1G60R30C1G60R30C1G60V982B5Y), name: ContractName("db-6") }, QualifiedContractIdentifier { issuer: StandardPrincipalData(S13GE1R70W3GE1R70W3GE1R70W3GE1R70ZZ512DY), name: ContractName("db-7") }, QualifiedContractIdentifier { issuer: StandardPrincipalData(S140G2081040G2081040G2081040G20813AC90JG), name: ContractName("db-8") }, QualifiedContractIdentifier { issuer: StandardPrincipalData(S14GJ289144GJ289144GJ289144GJ28917BTBK9Y), name: ContractName("db-9") }, QualifiedContractIdentifier { issuer: StandardPrincipalData(S150M2GA1850M2GA1850M2GA1850M2GA1BVWYVMM), name: ContractName("db-10") }, QualifiedContractIdentifier { issuer: StandardPrincipalData(S15GP2RB1C5GP2RB1C5GP2RB1C5GP2RB1CHKPY8A), name: ContractName("db-11") }]
 right: []
stack backtrace:
   0:     0x55de44413c12 - std::backtrace_rs::backtrace::libunwind::trace::hde5393a3699c97ba
                               at /rustc/2fa8b11f0933dae9b4e5d287cc10c989218e8b36/library/std/src/../../backtrace/src/backtrace/libunwind.rs:117:9
   1:     0x55de44413c12 - std::backtrace_rs::backtrace::trace_unsynchronized::h3ff2a1f207cc6214
                               at /rustc/2fa8b11f0933dae9b4e5d287cc10c989218e8b36/library/std/src/../../backtrace/src/backtrace/mod.rs:66:14
   2:     0x55de44413c12 - std::sys::backtrace::_print_fmt::h59669f906692834a
                               at /rustc/2fa8b11f0933dae9b4e5d287cc10c989218e8b36/library/std/src/sys/backtrace.rs:66:9
--
```


### test_walk_star_allowed_15
No failures detected for this test


Full test results are available in the uploaded artifacts.
